name: "Sheeju Alex"
description: "My technical blog!!"

author: "Sheeju Alex"

url: "http://sheeju.github.io"
baseurl: ""

markdown: kramdown 
permalink: :year/:month/:title.html

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Google Analytics
ga_domain: auto
ga_tracking_id: UA-61593707-1
