name: "Sheeju Alex"
description: "My technical blog!!"

author: "Sheeju Alex"

url: "http://sheeju.github.io"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: auto
ga_tracking_id: UA-61593707-1
